"""initial migration

Revision ID: 4b1803fcc8ef
Revises: 
Create Date: 2021-04-27 16:51:09.063729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4b1803fcc8ef"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookmarks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=True),
        sa.Column("url", sa.String(length=200), nullable=True),
        sa.Column("chrome_id", sa.Integer(), nullable=True),
        sa.Column("date_added", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bookmarks_title"), "bookmarks", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bookmarks_title"), table_name="bookmarks")
    op.drop_table("bookmarks")
    # ### end Alembic commands ###
